branch-defaults:
  cicd:
    environment: Carewatch-backend-env
environment-defaults:
  Carewatch-backend-env:
    branch: null
    repository: null
global:
  application_name: carewatch-backend
  default_ec2_keyname: demo
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
