name: Deploy to cicd

on:
  push:
    branches: [cicd]
  pull_request:
    branches: [cicd]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: cicsession
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy project to eb
        run: eb deploy
